Added some sample code and PixelFormat constants
stakx/stakx.WIC pull request #8
Opened 2019-06-29 13:19 UTC by jpmikkers

2019-06-29 14:33 UTC, stakx requested changes
Thanks a lot for the PR! :+1: I'll be very happy to merge your contributions, just two small suggestions regarding code convention consistency.

2019-06-29 14:33 UTC, stakx commented on WIC/Constants/WICPixelFormats.cs
> +        public static readonly Guid GUID_WICPixelFormatDontCare = new Guid(0x6fddc324, 0x4e03, 0x4bfe, 0xb1, 0x85, 0x3d, 0x77, 0x76, 0x8d, 0xc9, 0x00);
Could you please remove the `GUID_` name prefix from this and all following fields?

(I know that's what the documentation and original header files call it, but there's no added benefit in this prefix; I've taken some liberties with renaming things elsewhere to get a little closer to .NET's usual conventions.)

2019-06-29 14:33 UTC, stakx commented on WIC/Constants/WICPixelFormats.cs
> +    public static class WICPixelFormats
Consider renaming this class to `WICPixelFormat` (without `s`) for consistency with other preexisting enum-like typed in `Constants/`.

2019-06-29 20:44 UTC, jpmikkers commented
Done!

2019-06-29 21:29 UTC, stakx approved these changes

2019-06-29 21:31 UTC, merged

2019-06-29 21:34 UTC, stakx commented
Wonderful, thank you!

Now that the source code is no longer just by me, I'll probably need to update the copyright in the license file.

Let me know if you'd like me to push an updated package to NuGet.

2019-06-30 12:16 UTC, jpmikkers commented
Hi stakx, no that's not necessary, I barely touched the library.